_BASE_: "../../configs/PascalVOC-Detection/faster_rcnn_R_50_FPN.yaml"
MODEL:
#  USE_SOURCE: False #是否使用source网络或者是使用微调后的网络
  META_ARCHITECTURE: "CTAOD"
  ROI_HEADS:
    NUM_CLASSES: 3
  RESNETS:
    NORM: "FrozenBN"
INPUT:
  MIN_SIZE_TRAIN: (800, 832, 864, 896, 928, 960, 992, 1024)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TRAIN: 2048
  MAX_SIZE_TEST: 2048
DATASETS:
  TEST: ('ACDC_openset_fog_train_het-sem', 'ACDC_openset_night_train_het-sem','ACDC_openset_rain_train_het-sem', 'ACDC_openset_snow_train_het-sem', )

SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  STEPS: (50000, )
  MAX_ITER: 70000
  IMS_PER_BATCH: 1
  WARMUP_ITERS: 0

#hyperparameters
  CTAOD: TRUE
  MT: 0.9998
  RST_M: 0.0001
  LOSS_WEIGHT: 1.0
  THRESHOLD_INIT: 0.80
  THRESHOLD_MAX: 0.90
  THRESHOLD_MINI: 0.65
  ALPHA_DT: 1.3
  GAMMA_DT: 0.95
  PROPOSALS: 500
  SLOPE_LEN: 0
  SLOPE_THRESH: 0.0
  SCORE_EM: 0.5
  SCORE_GAMMA: 0.8
  SCORE_THRESH: 1.4

OUTPUT_DIR: /public/home/luya/code/CTTA_Openset/tools/output/CTTA_het3_5
SOURCE_DIR: /public/home/luya/code/CTTA_Openset/tools/output/source3_5
