_BASE_: "../../configs/PascalVOC-Detection/faster_rcnn_R_50_FPN.yaml"
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 8

DATASETS:
  TRAIN: ("cityscape_opensettrain",)
  TEST: ('cityscape_opensetval', 'cityscape_opensettest')
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  STEPS: (2500, 4000)
  MAX_ITER: 20000
  IMS_PER_BATCH: 64

OUTPUT_DIR: ./output/res50_shift
